### ISSUE TITLE
Melhorias que precisamos para o projeto carsPHP

### ISSUE THREAD

**Issue by VillyRosa** [lucasbrasantos/carsPHP#1]
Bom dia, Lucas Braga Santos! Venho te sugerir algumas melhorias para o projeto carsPHP para o tornar quem sabe mais agradável.

1 - Como é um projeto código aberto é importante incluir uma sql simplificada do banco que não seja muito pesada para rodarmos o projeto ou instruções dentro de um Readme.md para entendermos como executar o projeto.

2 - Percebi que nos scripts register e delete ambos scripts PHP, caso caia no bloco catch você imprime uma mensagem na tela de erro, tente especificar mais o erro para a etapa de desenvolvimento do projeto, uma ideia é utilizar a própria mensagem de erro da Exception, mas após liberar este projeto na web talvez seja mais interessante somente chamar uma tela / mensagem de alerta para o usuário final de que algo deu errado sem especificar para ele oque deu errado.

3 - Não é necessária a div container em todas as páginas, você pode adicionar a flex-box para alinhar os itens no próprio body.

4 - Remova comentários desnecessários do código, isso pode atrapalhar o entendimento dele no futuro.

5 - Já pensou em criar uma classe car? Trabalhar com programação orientada a objetos melhora o entendimento do seu código para outros desenvolvedores que futuramente trabalharam nele, aproveite para tipar as variáveis que devem ser recebidas em cada função para tornar o desenvolvimento mais fácil.

6 - Melhore a identação do código, em várias partes encontrei espaços desnecessários no código, isso não é bom para a legibilidade dele.

7 - O PDO é frequentemente recomendado para novos projetos devido à sua flexibilidade, recursos de segurança (como declarações preparadas) e portabilidade entre diferentes sistemas de banco de dados.

8 - Adicione validações de campos também pelo back-end com php, você não garante que o usuário preencherá todos os campos somente por que tem required nos inputs, isso pode ser facilmente removido no inspecionar página.

Obrigado pela atenção! Qualquer dúvida entre em contato.

**Comment by lucasbrasantos** [comment]
Olá, Villy Rosa!

Gostaria de informar que a issue no GitHub referente ao projeto carsPHP foi corrigida e está agora fechada. Abaixo estão as melhorias implementadas:

1. Incluímos uma SQL simplificada do banco ou instruções no arquivo `Readme.md` para facilitar a execução do projeto.
2. Ajustamos os scripts `register` e `delete` para fornecer mensagens mais específicas de erro durante a etapa de desenvolvimento, enquanto exibimos apenas mensagens de alerta genéricas para os usuários finais após a liberação do projeto na web.
3. Removemos a necessidade da `div container` em todas as páginas, optando por alinhar os itens usando `flex-box` diretamente no `body`.
4. Removemos comentários desnecessários do código para melhorar a legibilidade.
5. Criamos uma classe `Car` para melhorar a organização do código e facilitar o entendimento para outros desenvolvedores, além de tipar as variáveis para tornar o desenvolvimento mais fácil.
6. Melhoramos a identação do código, removendo espaços desnecessários para uma melhor legibilidade.
7. Implementamos o uso de `PDO` para melhorar a flexibilidade, segurança e portabilidade do projeto.
8. Adicionamos validações de campos no back-end com `PHP` para garantir que todos os campos obrigatórios sejam preenchidos antes de enviar os dados.

Agradecemos pela sua sugestão e estamos à disposição para quaisquer dúvidas ou sugestões adicionais. 

Atenciosamente,
Lucas Braga Santos
