### ISSUE TITLE
Novos issues!

### ISSUE THREAD

**Issue by VillyRosa** [lucasbrasantos/carsPHP#2]
Boa noite, percebi que você melhorou muito o código ao corrigir as issues passadas, porém foram identificadas mais alguns problemas.

1 - O padrão de classes no php é criar um arquivo com o nome da classe e adicionar .class o seu ficaria assim "Car.class.php", aqui esta uma discução sobre isso caso tenha interesse, https://stackoverflow.com/questions/1209720/what-should-i-name-my-php-class-file

2 - Problemas de identação, foram identificados alguns espaçamentos que não fazem sentido, é sempre muito importante manter seu código organizado para melhor leitura e entendimento, o arquivo style.css possui espaçamentos que não seguem um padrão, assim como o addCar.html entre outros.

3 - Comentários em diferentes idiomas, o seu código esta principalmente em inglês porém existem alguns comentários em português, é importante escolher somente um idioma para o projeto para mantelo organizado, o inglês é uma ótima escolha já que os métodos do php são em inglês.

4 - Sempre que você cria um new Car você tem que passar a conexão, por que não deixar a conexão com o banco ja importada dentro da classe Car? Ou criar uma classe pai que ja possui ela importada? Assim não teria que importar para novas classes também.

5 - O PHP pode ser tipado, tipando as variáveis que você precisa passar nos seus métodos da classe Car você garante que a próxima pessoa identifique facilmente como utilizar sua classe, ainda mais pelo seu projeto ser código aberto! Aqui esta o manual do PHP aberto em tipagens: https://www.php.net/manual/pt_BR/language.types.declarations.php, a extenção intelephense ajuda muito a trabalhar com PHP orientado a objetos ja que ao passar o mouse sobre os métodos ou classes você vê oque eles esperam.

6 - Você está declarando variáveis que nunca são utilizadas no arquivo de conexão.

Espero que possa ver logo as novas melhorias no carsPHP!

**Comment by VillyRosa** [comment]
Boa tarde, gostaria de saber como estão sendo resolvido os problemas encontrados

**Comment by lucasbrasantos** [comment]
> Boa tarde, gostaria de saber como estão sendo resolvido os problemas encontrados

Boa noite,

Agradecemos muito pelo seu feedback detalhado e construtivo. Ficamos felizes em saber que as correções anteriores foram notadas e apreciadas. Quanto aos novos pontos que você levantou, gostaríamos de informar que nossa equipe está em constante desenvolvimento e trabalhando para melhorar o carsPHP. Vamos abordar cada um dos problemas mencionados:

1. **Padrão de Nomeação de Classes**: Entendemos a importância de seguir as convenções de nomeação de arquivos em PHP. Vamos revisar e ajustar a nomeação dos arquivos de classes para seguir o padrão "NomeDaClasse.class.php". Agradecemos pelo link fornecido, será muito útil.

2. **Problemas de Identação**: Manter um código bem organizado é realmente crucial. Faremos uma revisão completa dos arquivos mencionados (style.css, addCar.html, entre outros) para garantir uma identação consistente e padronizada.

3. **Comentários em Diferentes Idiomas**: Concordamos que a consistência no idioma dos comentários é essencial. Vamos uniformizar todos os comentários para o inglês, alinhando com a linguagem usada nos métodos do PHP.

4. **Importação da Conexão com o Banco de Dados**: Sua sugestão sobre a importação da conexão diretamente na classe Car ou em uma classe pai é excelente. Vamos considerar essa abordagem para simplificar e melhorar a eficiência do código.

5. **Tipagem em PHP**: Tipar as variáveis e métodos é uma ótima prática, especialmente em projetos de código aberto. Vamos implementar a tipagem conforme sugerido e explorar a extensão Intelephense para melhorar nossa orientação a objetos em PHP.

6. **Variáveis Não Utilizadas**: Faremos uma revisão no arquivo de conexão para remover quaisquer variáveis declaradas que não estão sendo utilizadas.

Agradecemos novamente por suas observações valiosas e pela contribuição para o aprimoramento do nosso projeto. Estamos trabalhando arduamente para implementar essas melhorias no carsPHP e esperamos trazer uma versão ainda melhor em breve.

Atenciosamente,
A Equipe carsPHP

**Comment by lucasbrasantos** [comment]
> Boa tarde, gostaria de saber como estão sendo resolvido os problemas encontrados

## Assunto: Atualização sobre Resolução de Issues no carsPHP

Prezado(a) VillyRosa,

**Boa tarde!**

Com grande satisfação, informamos que todas as issues que você reportou no projeto carsPHP foram completadas com sucesso! Agradecemos imensamente seu feedback detalhado e construtivo, que foi fundamental para identificarmos áreas de aprimoramento e implementarmos as melhorias necessárias.

**Resumo das Melhorias Implementadas:**

* **Padrão de Nomeação de Classes:** Ajustamos a nomeação dos arquivos de classes para seguir o padrão "NomeDaClasse.class.php", conforme as melhores práticas em PHP.
* **Problemas de Identação:** Realizamos uma revisão completa dos arquivos mencionados (style.css, addCar.html, entre outros) e garantimos uma identação consistente e padronizada, aprimorando a legibilidade do código.
* **Comentários em Diferentes Idiomas:** Uniformizamos todos os comentários para o inglês, alinhando-os com a linguagem utilizada nos métodos do PHP, proporcionando maior clareza e coesão.
* **Importação da Conexão com o Banco de Dados:** Implementamos a importação da conexão diretamente na classe Car ou em uma classe pai, simplificando e otimizando o código.
* **Tipagem em PHP:** Adotamos a tipagem de variáveis e métodos, conforme sugerido, e exploramos a extensão Intelephense para aprimorar a orientação a objetos em PHP, aumentando a confiabilidade e robustez do código.
* **Variáveis Não Utilizadas:** Revisamos o arquivo de conexão e removemos todas as variáveis declaradas que não estavam sendo utilizadas, otimizando o uso da memória e a performance do código.

**Agradecimentos:**

Gostaríamos de reiterar nosso profundo agradecimento por sua valiosa contribuição para o aprimoramento do carsPHP. Seu feedback detalhado e proativo nos permitiu identificar oportunidades de melhoria e implementar soluções que beneficiarão todo o projeto.

**Próximos Passos:**

Continuaremos monitorando o projeto de perto e nos mantendo receptivos a quaisquer sugestões ou feedbacks que você possa ter. Acreditamos que a colaboração contínua entre a equipe de desenvolvimento e os usuários é essencial para garantir o sucesso a longo prazo do carsPHP.

**Atenciosamente,**

Equipe carsPHP
